---
- hosts: webservers
  #remote_user: vagrant
  become: true
  vars:
   download_url: http://download.oracle.com/otn-pub/java/jdk/8u171-b11/512cd62ec5174c3487ac17c61aaa89e8/jdk-8u171-linux-x64.rpm
  
  tasks:
  - name: Download JDK 8 RPM file
    yum:
      name: "{{ item }}"
      state: present
    with_items:
     openjdk-8-jdk 
    
  - name: Download Apache Maven 
    get_url: url=http://apache.claz.org/maven/maven-3/3.1.1/binaries/apache-maven--bin.tar.gz dest=/tmp/apache-maven-3.1.1-bin.tar.gz

  - name: Untar Maven 
    shell: chdir=/tmp creates=/opt/apache-maven-3.1.1 tar -zxf apache-maven-3.1.1-bin.tar.gz -C /opt

    # What is missing

  - name: Update path for maven use
    shell: export PATH=/opt/apache-maven-3.1.1/bin:$PATH
